openapi: 3.0.1
info:
  title: Note application API
  version: '1.0.0'
servers:
  - url: 'http://localhost:8080'
    description: local

paths:
  /note:
    post:
      tags:
        - Note
      operationId: saveNote
      description: 'Сохранить записку'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateNoteRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  #--------------------------------------------------------------------------------------------------------#
  /note/{accountId}:
    get:
      tags:
        - Note
      operationId: getNotesByAccountId
      description: 'Взять записку по accountId'
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NoteResponseList'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    delete:
      tags:
        - Note
      operationId: deleteNotesByAccountId
      description: 'Удалить записку по accountId'
      parameters:
        - name: accountId
          in: path
          required: true
          schema:
            type: integer
      responses:
        '204':
          description: No content
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
#--------------------------------------------------------------------------------------------------------#
components:
  schemas:
    CreateNoteRequest:
      type: object
      properties:
        accountId:
          type: integer
        name:
          type: string
        description:
          type: string
        link:
          type: string
    #--------------------------------------------------------------------------------------------------------#
    NoteResponse:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        link:
          type: string
        description:
          type: string
        accountId:
          type: integer
    #--------------------------------------------------------------------------------------------------------#
    NoteResponseList:
      type: object
      properties:
        objects:
          $ref: '#/components/schemas/NoteResponse'
        name:
          type: string
        link:
          type: string
    #--------------------------------------------------------------------------------------------------------#
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
        businessCode:
          type: integer
        error:
          type: string
        path:
          type: string