// Package noteSpec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package noteSpec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// CreateNoteRequest defines model for CreateNoteRequest.
type CreateNoteRequest struct {
	Description *string `json:"description,omitempty"`
	Link        *string `json:"link,omitempty"`
	Name        *string `json:"name,omitempty"`
	TgId        *int64  `json:"tgId,omitempty"`
}

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	BusinessCode *int    `json:"businessCode,omitempty"`
	Error        *string `json:"error,omitempty"`
	Path         *string `json:"path,omitempty"`
	Status       *int    `json:"status,omitempty"`
	Timestamp    *string `json:"timestamp,omitempty"`
}

// NoteResponse defines model for NoteResponse.
type NoteResponse struct {
	AccountId   *int    `json:"accountId,omitempty"`
	Description *string `json:"description,omitempty"`
	Id          *string `json:"id,omitempty"`
	Link        *string `json:"link,omitempty"`
	Name        *string `json:"name,omitempty"`
	TgId        *int64  `json:"tgId,omitempty"`
}

// NoteResponseList defines model for NoteResponseList.
type NoteResponseList struct {
	Objects *[]NoteResponse `json:"objects,omitempty"`
}

// SaveNoteJSONRequestBody defines body for SaveNote for application/json ContentType.
type SaveNoteJSONRequestBody = CreateNoteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /note)
	SaveNote(c *gin.Context)

	// (DELETE /note/{tgId})
	DeleteNotesByTgId(c *gin.Context, tgId int)

	// (GET /note/{tgId})
	GetNotesByTgId(c *gin.Context, tgId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// SaveNote operation middleware
func (siw *ServerInterfaceWrapper) SaveNote(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.SaveNote(c)
}

// DeleteNotesByTgId operation middleware
func (siw *ServerInterfaceWrapper) DeleteNotesByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "tgId" -------------
	var tgId int

	err = runtime.BindStyledParameterWithOptions("simple", "tgId", c.Param("tgId"), &tgId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tgId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.DeleteNotesByTgId(c, tgId)
}

// GetNotesByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetNotesByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "tgId" -------------
	var tgId int64

	err = runtime.BindStyledParameterWithOptions("simple", "tgId", c.Param("tgId"), &tgId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter tgId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetNotesByTgId(c, tgId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/note", wrapper.SaveNote)
	router.DELETE(options.BaseURL+"/note/:tgId", wrapper.DeleteNotesByTgId)
	router.GET(options.BaseURL+"/note/:tgId", wrapper.GetNotesByTgId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/8xVzWoUQRB+laH0OOxsNEqYm4kiQYmSeJMcOjOV3Y4z3WN1bWBZBvzBmyD4BuIL5CAk",
	"KCav0PNG0t3ZZDfbISKJ5Dbb1V0/30/tBApdN1qhYgP5BEwxxFr4zzVCwbihGTfx7QgNu8OGdIPEEv2V",
	"Ek1BsmGplfvJ4wYhB8Mk1QDaFCqp3kQDStQYDfBgvXSBXU21YMhBKn64DOn0plSMAyRo27MjvbOHBbvH",
	"T4g0baJptDK42O3OyEiFxqzpcrb4WcoU0CWI9tUIHkYDhgWPTDwdyxoNi7qJvIz1H7C+rH1RFHqkOOCz",
	"WOwqLmR5GyiaHfG5jGkq3PWfkrH2H3cJdyGHO9m5WLNTpWZzoJ2XFERiHOvBHUm1q/1skisXczkS0TSV",
	"LIQDMHn0ch1S2EcyHk5Y6vV7fZddN6hEIyGH+71+bwmCMnyTmdIcaNNhrjlGwH6zx92n7p09sL/tUfeh",
	"+5zYQ3tgT+xR997+7D6Cz06+AYcwbIl9bz9IgYIDV3U5dpkLrRiVLzLTdbZnAvcBmquAW/R368GhUzD9",
	"UPf6/WsrOM9Ue1Gz8OKZQ/jBNVacXwiRkuuKkZSoki2kfaTEPwiqEQMD+WsvDdh2J57fbOLk3wZ6KwyE",
	"XyD6u/1hD+yvKMmJPbHHCWOFAxJ1IssF1h/7tK6sWR2/cl5zGiNRIyO5liYgXRm/kaY2DaYMOpGEJeRM",
	"I0xnYJp3a9Su2wvcLy9Ot6GTKTW3lqwUBhhz4Fd72H35J1KeIt8wI39HyM2Y0S/iSw25HGTwfzheFWVC",
	"03V0a5eB+9/3dwL782kqXYgKUhhRBTkMmZs8y/zhUBvOV/orfWi32z8BAAD//+tw0/B6CQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
