// Package authSpec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package authSpec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateAccountRequestAccountType.
const (
	TG  CreateAccountRequestAccountType = "TG"
	WEB CreateAccountRequestAccountType = "WEB"
)

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Email            *string `json:"email,omitempty"`
	FirstName        *string `json:"firstName,omitempty"`
	Id               *int64  `json:"id,omitempty"`
	KeycloakId       *string `json:"keycloakId,omitempty"`
	LastName         *string `json:"lastName,omitempty"`
	TelegramId       *int64  `json:"telegramId,omitempty"`
	TelegramUserName *string `json:"telegramUserName,omitempty"`
	Username         *string `json:"username,omitempty"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	AccountType      *CreateAccountRequestAccountType `json:"accountType,omitempty"`
	Email            *string                          `json:"email,omitempty"`
	FirstName        *string                          `json:"firstName,omitempty"`
	LastName         *string                          `json:"lastName,omitempty"`
	TelegramId       *int64                           `json:"telegramId,omitempty"`
	TelegramUserName *string                          `json:"telegramUserName,omitempty"`
	Username         *string                          `json:"username,omitempty"`
}

// CreateAccountRequestAccountType defines model for CreateAccountRequest.AccountType.
type CreateAccountRequestAccountType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	BusinessCode *int    `json:"businessCode,omitempty"`
	Error        *string `json:"error,omitempty"`
	Path         *string `json:"path,omitempty"`
	Status       *int    `json:"status,omitempty"`
	Timestamp    *string `json:"timestamp,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AccountId *int64  `json:"accountId,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	Role      *string `json:"role,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = CreateAccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /account)
	RegisterAccount(c *gin.Context)

	// (POST /account/{telegramId})
	GetAccountByTgId(c *gin.Context, telegramId int64)

	// (GET /profile/{telegramId})
	GetProfileByTgId(c *gin.Context, telegramId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RegisterAccount operation middleware
func (siw *ServerInterfaceWrapper) RegisterAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAccount(c)
}

// GetAccountByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameterWithOptions("simple", "telegramId", c.Param("telegramId"), &telegramId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountByTgId(c, telegramId)
}

// GetProfileByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameterWithOptions("simple", "telegramId", c.Param("telegramId"), &telegramId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileByTgId(c, telegramId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/account", wrapper.RegisterAccount)
	router.POST(options.BaseURL+"/account/:telegramId", wrapper.GetAccountByTgId)
	router.GET(options.BaseURL+"/profile/:telegramId", wrapper.GetProfileByTgId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xVzUocQRB+laWS47Cz5g+Zm4rIEkjEGHIIe2hnamdbZ7on3TXCsgwYDeQi5JhjXmFJ",
	"kBgl5hV63ih0z6yu7qiLeEhCbkN1dX3VX331zQhCmWZSoCANwQh0OMCUuc+lMJS5oA3UmRQabShTMkNF",
	"HF0Cpown9oOGGUIAmhQXMRQe9LnS9IKl2HjKIxvuS5UyggC4oGdPwJvkcUEYo7KJOzgME8l2ulFjnYTd",
	"AEKYYKxY2p0XbHLhtUZ1bdVcoxLNh8V5Ubm1jSHZ9BWFjPCcyHc5aprlkVXnm+72CFDkKQRvYXMNPHiz",
	"ugw9b7aRu3L/53O2qpRU14tuK9dcoNYrMpquONUU2gKNnWSMBo0Hmhjlurkc8RQ1sTSbs/91Jfs8wetf",
	"UI97bpLnXhclk3uYgA1x0ZcumZMtCUs5DVoa1S6q1tJ6FzzYRaW5FBDAQrvT7lgUmaFgGYcAHrc77QWo",
	"+HZP9us3OzJktQMR6lDxjKoq5rMZl3vmyHwzx+X7cr/cM8flnjkzX8243C8PW2ZsTsyJGZcH5me5Dw5O",
	"MXvbEgkbGHNNqOpdAw9UtW7LMhpauFAKwqoDlmUJD91df1tb+Inv2a+HCvsQwAP/whj92hX9xn0uHGWq",
	"nrd776NO594wr9qwQ7tM3svnlv+n9wh6eQkbILuCrKaS1qtKFe5CJScWa2tfk0n0bHAiAH904THFDWr4",
	"Ys7MaXlQfjTH1fR/ucCh+T6RhDkyp+Und9CiuMWjGUmsIdU9LA83427kBKlYioTKdjgCbrGcKXhQ7ce0",
	"BVYS4gojCEjl6E1xd+s2Fr3/krhFEllllDOSiHE+RVh7KD+YsflhTu8qkNqs/zWBXP0H/S0Cqfu2ArF/",
	"ZZdWTeJypUSGLAEPcpVAAAOiLPB9FxxITcFiZ3EBil7xOwAA///8pCi13QoAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
