openapi: 3.0.1
info:
  title: Auth server API
  version: '1.0.0'
servers:
  - url: 'http://localhost:8081'
    description: local

paths:
  /account:
    post:
      tags:
        - Account
      operationId: registerAccount
      description: 'Зарегистрировать аккаунт'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateAccountRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AccountResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
#--------------------------------------------------------------------------------------------------------#
components:
  schemas:
    CreateAccountRequest:
      type: object
      properties:
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        login:
          type: string
        password:
          type: string
        accountType:
          type: string
          enum: [ "TG", "WEB" ]
        telegramId:
          type: integer
    #--------------------------------------------------------------------------------------------------------#
    AccountResponse:
      type: object
      properties:
        login:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
    #--------------------------------------------------------------------------------------------------------#
    ErrorResponse:
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
        businessCode:
          type: integer
        error:
          type: string
        path:
          type: string