// Package authSpec provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package authSpec

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CreateAccountRequestAccountType.
const (
	TG  CreateAccountRequestAccountType = "TG"
	WEB CreateAccountRequestAccountType = "WEB"
)

// AccountResponse defines model for AccountResponse.
type AccountResponse struct {
	Email            *string `json:"email,omitempty"`
	FirstName        *string `json:"firstName,omitempty"`
	Id               *int64  `json:"id,omitempty"`
	KeycloakId       *string `json:"keycloakId,omitempty"`
	LastName         *string `json:"lastName,omitempty"`
	TelegramId       *int64  `json:"telegramId,omitempty"`
	TelegramUserName *string `json:"telegramUserName,omitempty"`
	Username         *string `json:"username,omitempty"`
}

// CreateAccountRequest defines model for CreateAccountRequest.
type CreateAccountRequest struct {
	AccountType      *CreateAccountRequestAccountType `json:"accountType,omitempty"`
	Email            *string                          `json:"email,omitempty"`
	FirstName        *string                          `json:"firstName,omitempty"`
	LastName         *string                          `json:"lastName,omitempty"`
	TelegramId       *int64                           `json:"telegramId,omitempty"`
	TelegramUserName *string                          `json:"telegramUserName,omitempty"`
	Username         *string                          `json:"username,omitempty"`
}

// CreateAccountRequestAccountType defines model for CreateAccountRequest.AccountType.
type CreateAccountRequestAccountType string

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	BusinessCode *int    `json:"businessCode,omitempty"`
	Error        *string `json:"error,omitempty"`
	Path         *string `json:"path,omitempty"`
	Status       *int    `json:"status,omitempty"`
	Timestamp    *string `json:"timestamp,omitempty"`
}

// ProfileResponse defines model for ProfileResponse.
type ProfileResponse struct {
	AccountId *int64  `json:"accountId,omitempty"`
	Id        *int64  `json:"id,omitempty"`
	Role      *string `json:"role,omitempty"`
	Username  *string `json:"username,omitempty"`
}

// RegisterAccountJSONRequestBody defines body for RegisterAccount for application/json ContentType.
type RegisterAccountJSONRequestBody = CreateAccountRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /account)
	RegisterAccount(c *gin.Context)

	// (GET /account/{telegramId})
	GetAccountByTgId(c *gin.Context, telegramId int64)

	// (GET /profile/{telegramId})
	GetProfileByTgId(c *gin.Context, telegramId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// RegisterAccount operation middleware
func (siw *ServerInterfaceWrapper) RegisterAccount(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.RegisterAccount(c)
}

// GetAccountByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetAccountByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameterWithOptions("simple", "telegramId", c.Param("telegramId"), &telegramId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetAccountByTgId(c, telegramId)
}

// GetProfileByTgId operation middleware
func (siw *ServerInterfaceWrapper) GetProfileByTgId(c *gin.Context) {

	var err error

	// ------------- Path parameter "telegramId" -------------
	var telegramId int64

	err = runtime.BindStyledParameterWithOptions("simple", "telegramId", c.Param("telegramId"), &telegramId, runtime.BindStyledParameterOptions{Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter telegramId: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetProfileByTgId(c, telegramId)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/account", wrapper.RegisterAccount)
	router.GET(options.BaseURL+"/account/:telegramId", wrapper.GetAccountByTgId)
	router.GET(options.BaseURL+"/profile/:telegramId", wrapper.GetProfileByTgId)
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xVz0ocTxB+laV+v+Ows+YfMjcVkSWQiDHkEPbQztTOts5MT6prhGVZMBrIRcgxx7zC",
	"kiAxSswr9LxR6J5ZXXWMi3hIQm5DdXV91V999c0IQpXmKsOMNQQj0OEAU+E+l8JQFRlvoM5VptGGclI5",
	"Ekt0CZgKmdgPHuYIAWgmmcUw9qAvSfMzkWLjqYxsuK8oFQwByIyfPAJvmiczxhjJJu7gMEyU2OlGjXUS",
	"8QsQxgRjEml3XrDphZca6caqhUbKmg/H50XV1jaGbNNXCAXjOZFvCtR8nUdRnW+62yPArEgheA2ba+DB",
	"q9Vl6HnXG7kr978/Z6tEim4W3VahZYZar6hotuJMU2gLNHaSCx40HmgWXOjmcixT1CzSfM7+10n1ZYI3",
	"v6Ae99wkz70upJJ7mIANyayvXLJkWxKWCh60NNIuUmtpvQse7CJpqTIIYKHdaXcsisoxE7mEAB62O+0F",
	"qPh2T/brNzsyVLUDEeqQZM5VFfPRTMo9c2S+mOPybblf7pnjcs+cmc9mUu6Xhy0zMSfmxEzKA/O93AcH",
	"R8LetkTCBsZSM1K9a+ABVeu2rKKhhQtVxlh1IPI8kaG7629rCz/1Pfv1P2EfAvjPvzBGv3ZFv3Gfx44y",
	"quft3vug07k3zKs27NAuk/f8qeX/8T2CXl7CBshuxlZTSetFpQp3oZKTiLW1r+kkejY4FYA/uvCYsW0i",
	"xiYxfDJn5rQ8KN+b42r4P1zg0HydKsIcmdPygztocdyS0TVFrCHXLSwPN+Nu5PRIIkVGsg2OQFos5wke",
	"VOsx64CVgiRhBAFTgd4Mdbcu47j3TxG3KCKvfPLOirDuUL4zE/PNnN5VILVX/20CufoL+lMEUvdtBWJ/",
	"yi6tmsTlSokKRQIeFJRAAAPmPPB9FxwozcFiZ3EBxr3xzwAAAP//o8vIC9wKAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
